### ISSUE TITLE
AttributeError : 'Material' object has no attribute 'textures'

### ISSUE THREAD

**Issue by DukeT** [kiniou/blender-nds-exporter#1]
I installed first python2.6.4 then
I installed blender(1263_BF25_SVN_26695)
(I don't exactly)
and unzip blender-nds-exporter-0.3-alpha
then move them .blender\script\io folder

I launching blender and create cube then
set Material, Texture and export NitendoDScallList.

but, error message come out on the console window

AttributeError : 'Material' object has no attribute 'textures'

**Comment by kiniou** [comment]
Hi Duke,
Could you try again with the following download : http://github.com/downloads/kiniou/blender-nds-exporter/blender-nds-exporter-0.3-1-alpha.zip
or
http://blog.knokorpo.fr/wp-content/uploads/2010/01/blender-nds-exporter-0.3-1-alpha.zip
I think it's the same issue with Blender API when they changed the "textures" attribute by "texture_slot" in the Material class.

**Comment by kiniou** [comment]
I close this bug as it seems to solved by installing the v0.3-1-alpha version of the script.
